pipeline:
  type: SimpleIntegrationTestPipeline
  epochs: 2
  batches_per_epoch: 2
trackers:
- type: DBTracker
  name: db_tracker
- type: PerformanceTracker
  name: performance_tracker
  monitoring_interval: 0.1
  test_mode: true
  lightweight_mode: true
callbacks:
- type: MetricsTracker
