#####################################################################################
#   Environment Configuration for Custom Metrics Test                              #
#####################################################################################

workspace: "outputs/custom_metrics_test"
verbose: true
debug: false
device: cpu

# Trackers for testing custom metrics with multiple key-value pairs
trackers:
  - type: "LogTracker"
    name: "log"
    verbose: true
  - type: "DBTracker"
    name: "experiment.db"
    verbose: true
  - type: "MLflowTracker"
    name: "custom_metrics_test"
    verbose: true
  - type: "TensorBoardTracker"
    name: "custom_metrics_test"
    verbose: true
  - type: "PerformanceTracker"
    name: "performance"
    verbose: true
