name: test_experiment
desc: a simple experiment
settings:
  pipeline:
    type: DummyPipeline
    epochs: 3
    batch_size: 64
    validation_split: 0.2
    test_split: 0.2
    shuffle: true
    callbacks: null
trials: null
